version: '3.5'
# 网络配置
networks:
  chess:
    driver: bridge

# 服务容器配置
services:

  user-rpc: # 自定义容器名称
    build:
      context: service/app/user              # 指定构建使用的 Dockerfile 文件
      dockerfile: rpc/Dockerfile
    environment: # 设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: # 设置端口映射
      - "4002:4002"  # user服务rpc端口
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - chess
    restart: always                      # 指定容器退出后的重启策略为始终重启

  user-api: # 自定义容器名称
    build:
      context: service/app/user               # 指定构建使用的 Dockerfile 文件
      dockerfile: api/Dockerfile
    environment: # 设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: # 设置端口映射
      - "4001:4001"  # user服务api端口
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - chess
    restart: always                      # 指定容器退出后的重启策略为始终重启
  
  chat-api: # 自定义容器名称
    build:
      context: service/app/chat              # 指定构建使用的 Dockerfile 文件
      dockerfile: api/Dockerfile
    environment: # 设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: # 设置端口映射
      - "4003:4003"  # user服务api端口
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - chess
    restart: always                      # 指定容器退出后的重启策略为始终重启

