// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"chess/service/app/chat/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/room",
					Handler: chatHandler(serverCtx),
				},
			}...,
		),
	)
}
